INSERT INTO simulator.teams(id, name)
VALUES (0, 'Saudi Arabia'),
       (1, 'Qatar'),
       (2, 'Costa Rica'),
       (3, 'Canada'),
       (4, 'Australia'),
       (5, 'Ghana'),
       (6, 'Iran'),
       (7, 'South Korea'),
       (8, 'Cameroon'),
       (9, 'Ecuador'),
       (10, 'Japan'),
       (11, 'Tunisia'),
       (12, 'Mexico'),
       (13, 'Morocco'),
       (14, 'Senegal'),
       (15, 'United States'),
       (16, 'Wales'),
       (17, 'Serbia'),
       (18, 'Poland'),
       (19, 'Croatia'),
       (20, 'Uruguay'),
       (21, 'Switzerland'),
       (22, 'Portugal'),
       (23, 'Denmark'),
       (24, 'Belgium'),
       (25, 'England'),
       (26, 'Spain'),
       (27, 'France'),
       (28, 'Germany'),
       (29, 'Netherlands'),
       (30, 'Argentina'),
       (31, 'Brazil');