spring:
  profiles:
    active: ${profile:development}
  application:
    name: World Cup Simulator (${spring.profiles.active})
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # FIX FOR: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
        temp.use_jdbc_metadata_defaults: false
        # Because detection is disabled you have to set correct dialect by hand.
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.batch_size: 20
        ddl-auto: validate
        generate_statistics: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: s3cr3t
  redis:
    host: 127.0.0.1

---

spring:
  config:
    activate:
      on-profile: development
  r2dbc:
    url: "r2dbc:postgresql://127.0.0.1:5432/simulator_dev"
    username: postgres
    password: s3cr3t
  flyway:
    url: "jdbc:postgresql://127.0.0.1:5432/simulator_dev"

server:
  error:
    include-stacktrace: ON_PARAM
    include-exception: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

probabilities:
  endpoint: http://127.0.0.1:81/

---

spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: "r2dbc:postgresql://127.0.0.1:5432/simulator_test"
    username: postgres
    password: s3cr3t
  flyway:
    url: "jdbc:postgresql://127.0.0.1:5432/simulator_test"

probabilities:
  endpoint: http://127.0.0.1:81/

---

spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: "r2dbc:postgresql://postgres:5432/simulator_dev"
    username: postgres
    password: s3cr3t
  flyway:
    url: "jdbc:postgresql://postgres:5432/simulator_dev"
  redis:
    host: redis

probabilities:
  endpoint: http://probabilities:81/
